title: Quantitative Portfolio Engine
description: Institutional-grade quantitative analysis and execution pipeline.
theme: jekyll-theme-primer
google_analytics: 
show_downloads: true

# Navigation links
nav:
  - text: Home
    url: /
  - text: GitHub
    url: https://github.com/mdc21/quantitative-portfolio-engine
